// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AtlasERP.Models;

public partial class Agenciagarantium
{
    public int Id { get; set; }

    public string Codagencia { get; set; }

    public string Codcia { get; set; }

    public string Coduser { get; set; }

    public DateTime? Feccrea { get; set; }

    public string Codmaq { get; set; }
}