// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AtlasERP.Models;

public partial class Asesorcliente
{
    public int Id { get; set; }

    public string Coduser { get; set; }

    public string Codcliente { get; set; }

    public string Usercrea { get; set; }

    public DateTime? Fecrea { get; set; }
}