// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AtlasERP.Models;

public partial class Asignacionmaquinacliente
{
    public int Id { get; set; }

    public string Codprod { get; set; }

    public string Codagencia { get; set; }

    public DateTime? Fecasign { get; set; }

    public string Codusercrea { get; set; }

    public int? Estado { get; set; }

    public string Observacion { get; set; }

    public string Ccia { get; set; }
}