// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AtlasERP.Models;

public partial class Auditorium
{
    public string Codaudit { get; set; }

    public string Accion { get; set; }

    public int? Codmodulo { get; set; }

    public string Codusuario { get; set; }

    public string Cod { get; set; }

    public string Ip { get; set; }

    public DateTime? Fecinteraccion { get; set; }

    public string Informacion { get; set; }

    public DateTime? Fecfinal { get; set; }
}