// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AtlasERP.Models;

public partial class AuditApp
{
    public decimal? ConsumoMb { get; set; }

    public int? Milisegundos { get; set; }

    public string Api { get; set; }

    public string Coduser { get; set; }

    public DateTime? Fechaconsumo { get; set; }

    public string Ip { get; set; }

    public int Id { get; set; }

    public string Method { get; set; }
}