// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AtlasERP.Models;

public partial class Bodega
{
    public int Id { get; set; }

    public string Nombrebodega { get; set; }

    public string Descripcion { get; set; }

    public DateTime? Fecrea { get; set; }

    public string Codusercrea { get; set; }

    public string Ccia { get; set; }

    public string Ccli { get; set; }
}