// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AtlasERP.Models;

public partial class Cardinal
{
    public int Id { get; set; }

    public string Nombrelocalizacion { get; set; }

    public DateTime? Feccrea { get; set; }

    public string Codusercrea { get; set; }

    public int? Idlocalidad { get; set; }

    public string CampoA { get; set; }

    public int? CampoB { get; set; }

    public string Codagencia { get; set; }

    public string Codtecnico { get; set; }
}