// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AtlasERP.Models;

public partial class Ccium
{
    public int Id { get; set; }

    public string Nombre { get; set; }

    public string Descripcion { get; set; }

    public decimal? Iva { get; set; }

    public string Logotipo { get; set; }

    public string Telf { get; set; }

    public string Direccion { get; set; }

    public string Type { get; set; }

    public string Email { get; set; }

    public string Ruc { get; set; }
}