// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AtlasERP.Models;

public partial class Cronograma1
{
    public string Codcrono { get; set; }

    public string Codusertecnic { get; set; }

    public string Codagencia { get; set; }

    public string Observacion { get; set; }

    public DateTime? Feccrea { get; set; }

    public string Codusercreacrono { get; set; }

    public int? Semanainicio { get; set; }

    public int? Mes { get; set; }

    public int? Dia { get; set; }

    public int? Anio { get; set; }

    public DateTime? Fechamantenimiento { get; set; }

    public int? Maquinasmanuales { get; set; }

    public string Codlocalidad { get; set; }

    public int? Estado { get; set; }
}