// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AtlasERP.Models;

public partial class DenominacionesCaja
{
    public int Id { get; set; }

    public int IdOperacion { get; set; }

    public string TipoOperacion { get; set; }

    public int? OneCent { get; set; }

    public int? FiveCent { get; set; }

    public int? TenCent { get; set; }

    public int? TwentyFiveCent { get; set; }

    public int? FiftyCent { get; set; }

    public int? OneDollarCoin { get; set; }

    public int? OneDollarBill { get; set; }

    public int? TwoDollars { get; set; }

    public int? FiveDollars { get; set; }

    public int? TenDollars { get; set; }

    public int? TwentyDollars { get; set; }

    public int? FiftyDollars { get; set; }

    public int? OneHundredDollars { get; set; }

    public string UsuarioRegistro { get; set; }

    public string Ccia { get; set; }

    public DateTime? Fecrea { get; set; }

    public int? Estado { get; set; }

    public int? Permisos { get; set; }
}