// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace AtlasERP.Models
{
    public partial class detalleCronoResult
    {
        public string nombrebodega { get; set; }
        public string descripBodega { get; set; }
        public string nombreCliente { get; set; }
        public string replegal { get; set; }
        public DateTime? fechaCreacionCrono { get; set; }
        public DateTime? fechamantenimiento { get; set; }
        public string nombreAgencia { get; set; }
        public string frecuencia { get; set; }
        public int? maquinasManuales { get; set; }
        public int? maquinasReales { get; set; }
        public string direccion { get; set; }
        public string longitud { get; set; }
        public string latitud { get; set; }
        public string horarioatenciond { get; set; }
        public string horarioatencionh { get; set; }
        public string horarioatenciondm { get; set; }
        public string horarioatencionhm { get; set; }
    }
}
