// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace AtlasERP.Models
{
    public partial class detalleCronoUnitResult
    {
        public string tecnico { get; set; }
        public string cedulaTecnico { get; set; }
        public string residenciaProvinciaTecnico { get; set; }
        public string residenciaCantonTecnico { get; set; }
        public string licenciaTecnico { get; set; }
        public string codLicencia { get; set; }
        public string ususarioAsignoMaquina { get; set; }
        public string usuarioCreadoCrono { get; set; }
        public string nserie { get; set; }
        public string nombreTipoMaquina { get; set; }
        public string nombremarca { get; set; }
        public string nombremodelo { get; set; }
        public int? contadorinicial { get; set; }
        public string observacion { get; set; }
        public int? contadorfinal { get; set; }
        public int? id { get; set; }
        public string nombrebodega { get; set; }
        public string descripBodega { get; set; }
        public string nombreCliente { get; set; }
        public string replegal { get; set; }
        public string codagencia { get; set; }
        public DateTime? fechaCreacionCrono { get; set; }
        public DateTime? fechamantenimiento { get; set; }
        public string nombreAgencia { get; set; }
        public string frecuencia { get; set; }
        public int? maquinasManuales { get; set; }
        public int? maquinasReales { get; set; }
        public string direccionAgencia { get; set; }
        public string longitud { get; set; }
        public string latitud { get; set; }
        public string horarioatenciond { get; set; }
        public string horarioatencionh { get; set; }
        public string horarioatenciondm { get; set; }
        public string horarioatencionhm { get; set; }
    }
}
