// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AtlasERP.Models;

public partial class DimDate
{
    public int DateKey { get; set; }

    public DateOnly Date { get; set; }

    public string DayOfWeek { get; set; }

    public int? DayOfMonth { get; set; }

    public string MonthName { get; set; }

    public int? MonthNumber { get; set; }

    public int? Year { get; set; }

    public bool? IsWeekend { get; set; }
}