// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AtlasERP.Models;

public partial class Empresa
{
    public string Codcia { get; set; }

    public string Nombre { get; set; }

    public string Descripcion { get; set; }

    public string Ruc { get; set; }

    public string Direccion { get; set; }

    public string Telf1 { get; set; }

    public string Telf2 { get; set; }

    public string Provincia { get; set; }

    public string Canton { get; set; }

    public decimal? Iva { get; set; }

    public decimal? OIimp { get; set; }

    public string LogotipoUrl { get; set; }

    public string Slogan { get; set; }

    public string TextoCotizacion { get; set; }

    public string NombrePersCargo { get; set; }

    public string Cargo { get; set; }

    public string Email { get; set; }

    public string Website1 { get; set; }

    public string Website2 { get; set; }

    public string FirmaRepLegal { get; set; }

    public string TypeCia { get; set; }
}