// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AtlasERP.Models;

public partial class Entytrancab
{
    public string Codtran { get; set; }

    public DateTime? Fecrea { get; set; }

    public string Nombre { get; set; }

    public string Serie { get; set; }

    public string Observacion { get; set; }

    public string Codusercrea { get; set; }

    public string Tipo { get; set; }

    public int? Estado { get; set; }

    public string Ccia { get; set; }

    public string Codbodent { get; set; }

    public string Codbodsal { get; set; }
}