// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AtlasERP.Models;

public partial class Entytrandet
{
    public string Codtrandet { get; set; }

    public string Codtran { get; set; }

    public string Descripcion { get; set; }

    public string Codusercrea { get; set; }

    public string Codprod { get; set; }

    public DateTime? Fecrea { get; set; }
}