// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AtlasERP.Models;

public partial class FileControl
{
    public int Id { get; set; }

    public string Url { get; set; }

    public string Tipo { get; set; }

    public DateTime? Fecrea { get; set; }

    public string Coduser { get; set; }
}