// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AtlasERP.Models;

public partial class FileMediaTicket
{
    public int Id { get; set; }

    public DateTime Fecrea { get; set; }

    public string Usercrea { get; set; }

    public string FileUrl { get; set; }

    public int? IdTicketRequerimiento { get; set; }

    public string Observacion { get; set; }

    public int? Estado { get; set; }

    public int? Permisos { get; set; }

    public string Type { get; set; }
}