// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AtlasERP.Models;

public partial class Garantia
{
    public string Codgarantia { get; set; }

    public string Descripcionbreve { get; set; }

    public string Codfrec { get; set; }

    public int? Tipo { get; set; }

    public DateTime? Fecusercrea { get; set; }

    public string Coduser { get; set; }

    public string Nombre { get; set; }

    public string Codtipomant { get; set; }

    public string Ccia { get; set; }
}