// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using AtlasERP.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace AtlasERP.Models
{
    public partial interface IatlasErpContextProcedures
    {
        Task<int> ActualizarAgenciaEstadoAsync(int? st, string codAgencia, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> calculoAsignacionCronogramaAsync(string codFecuency, string codcrono, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> CambioEstadosAsync(string codMensaje, int? state, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<CantidadAgenMaquiResult>> CantidadAgenMaquiAsync(string type, string filter, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> CliBodegAsignAsync(string codcli, int? id, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> CrearCuentaAsync(string codUser, string codCia, string tipoCuenta, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<CrearCuentaHelpDeskResult>> CrearCuentaHelpDeskAsync(string codCli, string codcia, string rol, string nombre, string apellido, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<detalleCronoResult>> detalleCronoAsync(int? tipo, string idcrono, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<detalleCronoUnitResult>> detalleCronoUnitAsync(int? tipo, string identidad, int? mes, int? dia, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> EliminarMaquinariaAsync(string codEntidad, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> generarCronogramaAsync(int? mes, int? anio, string agencia, string usertecnic, int? codLocal, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> IMGGeneralControlAsync(string codentidad, string IMG, string tipoImagen, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<ImgProductResult>> ImgProductAsync(string codmaquina, string img, string type, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<LoginCLientResult>> LoginCLientAsync(string email, string password, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<MaquinariaAgenciaResult>> MaquinariaAgenciaAsync(string filter, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<MaquinariaBodegaClienteResult>> MaquinariaBodegaClienteAsync(string codcliente, string ccia, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<ObetenerTecnicoProvinciasResult>> ObetenerTecnicoProvinciasAsync(string ccuser, string ccia, int? tp, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<ObtenerAgenciasResult>> ObtenerAgenciasAsync(string ccia, string filter, string codProv, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<obtenerAgenciasCardinalResult>> obtenerAgenciasCardinalAsync(string ccli, string ccia, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<ObtenerAgenciasLocalidadResult>> ObtenerAgenciasLocalidadAsync(int? localidadId, string zonificacion, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<ObtenerAsignacionTecnicoReuqerimientoResult>> ObtenerAsignacionTecnicoReuqerimientoAsync(int? idRequer, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<ObtenerBodegasResult>> ObtenerBodegasAsync(string ccia, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<ObtenerCantidadAgenciasProvResult>> ObtenerCantidadAgenciasProvAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<ObtenerCLientesResult>> ObtenerCLientesAsync(string ccia, int? type, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<ObtenerConsumoAppResult>> ObtenerConsumoAppAsync(int? tipo, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<ObtenerContratosResult>> ObtenerContratosAsync(string codcia, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<ObtenerCotizacionResult>> ObtenerCotizacionAsync(int? idTicket, string codcia, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<ObtenerCronoResult>> ObtenerCronoAsync(string ccia, int? anio, int? mes, int? localidad, int? tipo, string userTecnic, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<ObtenerEmpresaResult>> ObtenerEmpresaAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<obtenerGruposMarcasMaqResult>> obtenerGruposMarcasMaqAsync(string codigo, string codMarca, int? tipo, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<ObtenerItemsBodegasResult>> ObtenerItemsBodegasAsync(int? codbodega, int? state, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<ObtenerMaquinariaResult>> ObtenerMaquinariaAsync(string codcia, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<ObtenerMaquinasSinBodegaResult>> ObtenerMaquinasSinBodegaAsync(string codcia, int? option, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<ObtenerMaquinaUnitResult>> ObtenerMaquinaUnitAsync(string tpm, string mc, string mod, int? tp, string codmaq, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<ObtenerMensajesResult>> ObtenerMensajesAsync(string codUser, int? tipo, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<ObtenerMensajesTIcketResult>> ObtenerMensajesTIcketAsync(int? idRequerimiento, int? top, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<ObtenerRepuestosResult>> ObtenerRepuestosAsync(string usercrea, string codcia, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<ObtenerRepuestosRequerimientosResult>> ObtenerRepuestosRequerimientosAsync(int? idRequer, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<ObtenerTecniCronoResult>> ObtenerTecniCronoAsync(int? idlocalidad, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<ObtenerTicketsRequerimientosResult>> ObtenerTicketsRequerimientosAsync(string codcli, string ccia, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<ObtenerUsuariosResult>> ObtenerUsuariosAsync(string codCia, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<ObtenerUsuarioUnitResult>> ObtenerUsuarioUnitAsync(string coduser, string email, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> ProcesoTransdferenciaBodAsync(string codprod, int? state, string codusercrea, int? boden, int? bodsal, string ccia, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<ReporteMantenimientoResult>> ReporteMantenimientoAsync(string tipoentidad, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<ReporteTecnicoCorrectivoResult>> ReporteTecnicoCorrectivoAsync(int? idTicket, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> UpdateEstadoModuloAsync(int? permiso, string idmod, string coduser, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
