// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AtlasERP.Models;

public partial class Invmov
{
    public string Codmov { get; set; }

    public string Codtrancab { get; set; }

    public DateTime? Feccrea { get; set; }

    public string Tipomov { get; set; }

    public string Movcab { get; set; }

    public int? State { get; set; }
}