// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace AtlasERP.Models
{
    public partial class LoginCLientResult
    {
        public string coduser { get; set; }
        public string email { get; set; }
        public string contrasenia { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public string nombreProvincia { get; set; }
        public string nombreCanton { get; set; }
        public string cedula { get; set; }
        public string estado { get; set; }
        public string codSexo { get; set; }
        public string telf { get; set; }
        public string direccion { get; set; }
    }
}
