// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AtlasERP.Models;

public partial class Mantemaqcro
{
    public int Idmantenimiento { get; set; }

    public string Codcrono { get; set; }

    public string Codtecnico { get; set; }

    public DateTime? Feciniciomante { get; set; }

    public DateTime? Feccrea { get; set; }

    public DateTime? Fecfinmant { get; set; }

    public TimeOnly? Horainit { get; set; }

    public TimeOnly? Horafin { get; set; }

    public string Usercrea { get; set; }

    public string Codprod { get; set; }

    public int? Estado { get; set; }

    public int? IdRequer { get; set; }
}