// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AtlasERP.Models;

public partial class Maquinarium
{
    public string Codmaquina { get; set; }

    public string Codtipomaquina { get; set; }

    public string Observacion { get; set; }

    public string Modelo { get; set; }

    public string Marca { get; set; }

    public string Nserie { get; set; }

    public string Ninventario { get; set; }

    public string Codigobp { get; set; }

    public string Codusercrea { get; set; }

    public DateTime? Feccrea { get; set; }

    public string Codcia { get; set; }

    public int? Contadorinicial { get; set; }

    public int? Contadorfinal { get; set; }

    public int? Estado { get; set; }

    public decimal? Vidautil { get; set; }

    public decimal? ValorCompra { get; set; }

    public decimal? PorcentajeVenta { get; set; }

    public decimal? DesccuentoAplicable { get; set; }
}