// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace AtlasERP.Models
{
    public partial class MaquinariaAgenciaResult
    {
        public string cliente { get; set; }
        public string agencia { get; set; }
        public string codagencia { get; set; }
        public string modelo { get; set; }
        public string marca { get; set; }
        public string tipomaquina { get; set; }
    }
}
