// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace AtlasERP.Models
{
    public partial class MaquinariaBodegaClienteResult
    {
        public string codcliente { get; set; }
        public string codmaquina { get; set; }
        public string codtipomaquina { get; set; }
        public string observacion { get; set; }
        public string nombremarca { get; set; }
        public string nombremodelo { get; set; }
        public string codmodelo { get; set; }
        public string codmarca { get; set; }
        public string nserie { get; set; }
        public string ninventario { get; set; }
        public string codigobp { get; set; }
        public string codusercrea { get; set; }
        public DateTime? feccrea { get; set; }
        public string codcia { get; set; }
        public int? contadorinicial { get; set; }
        public int? contadorfinal { get; set; }
        public int? codbodega { get; set; }
        public string nombrebodega { get; set; }
        public string nombre { get; set; }
        public string nombrecliente { get; set; }
    }
}
