// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AtlasERP.Models;

public partial class Marca
{
    public string Codigotipomaq { get; set; }

    public string Codmarca { get; set; }

    public string Nombremarca { get; set; }
}