// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AtlasERP.Models;

public partial class ModeloMarcaRepuesto
{
    public int Id { get; set; }

    public string NombreModeloRep { get; set; }

    public DateTime Fecrea { get; set; }

    public string Usercrea { get; set; }

    public int? IdMarcaRepuestos { get; set; }

    public string CampoA { get; set; }
}