// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AtlasERP.Models;

public partial class ModulosEstante
{
    public int Id { get; set; }

    public string Row { get; set; }

    public string Col { get; set; }

    public string Description { get; set; }

    public int? Estado { get; set; }

    public int? IdEstante { get; set; }

    public string TokenId { get; set; }
}