// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace AtlasERP.Models
{
    public partial class ObetenerTecnicoProvinciasResult
    {
        public int id { get; set; }
        public string coduser { get; set; }
        public string codcia { get; set; }
        public string codprov { get; set; }
        public string nombreProvincia { get; set; }
        public string codcanton { get; set; }
        public string nombreCanton { get; set; }
        public string codmantenimiento { get; set; }
        public string codusermod { get; set; }
        public string nombreUsuarioModificacion { get; set; }
        public DateTime? fechainicio { get; set; }
        public DateTime? fechamod { get; set; }
    }
}
