// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace AtlasERP.Models
{
    public partial class ObtenerMaquinaUnitResult
    {
        public string imagen { get; set; }
        public string codmaquina { get; set; }
        public string codtipomaquina { get; set; }
        public string observacion { get; set; }
        public string modelo { get; set; }
        public string marca { get; set; }
        public string nserie { get; set; }
        public string ninventario { get; set; }
        public string codigobp { get; set; }
        public string codusercrea { get; set; }
        public DateTime? feccrea { get; set; }
        public string codcia { get; set; }
        public int? contadorinicial { get; set; }
        public int? contadorfinal { get; set; }
        public int? estado { get; set; }
        public decimal? vidautil { get; set; }
        public decimal? valorCompra { get; set; }
        public decimal? porcentajeVenta { get; set; }
        public decimal? desccuentoAplicable { get; set; }
    }
}
