// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace AtlasERP.Models
{
    public partial class ObtenerAgenciasResult
    {
        public int? cantidadMaquinaAgencia { get; set; }
        public string mantenimiento { get; set; }
        public string tipoAgencia { get; set; }
        public string provincia { get; set; }
        public string canton { get; set; }
        public string nombreCliente { get; set; }
        public string ruc { get; set; }
        public string codagencia { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public string observacion { get; set; }
        public string longitud { get; set; }
        public string latitud { get; set; }
        public string tipo { get; set; }
        public int? campoA { get; set; }
        public string campoB { get; set; }
        public string codcliente { get; set; }
        public string horarioatenciond { get; set; }
        public string codfrecuencia { get; set; }
        public string codcia { get; set; }
        public int? estado { get; set; }
        public string codProv { get; set; }
        public string codCanton { get; set; }
        public string horarioatencionh { get; set; }
        public string horarioatenciondm { get; set; }
        public string horarioatencionhm { get; set; }
        public int? centrocostos { get; set; }
        public DateTime? fecrea { get; set; }
    }
}
