// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace AtlasERP.Models
{
    public partial class ObtenerContratosResult
    {
        public string usuarioCargo { get; set; }
        public string nombre { get; set; }
        public string replegal { get; set; }
        public int codcontrato { get; set; }
        public string descripcion { get; set; }
        public DateTime? fecinicial { get; set; }
        public DateTime? fecfinal { get; set; }
        public int? estado { get; set; }
    }
}
