// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace AtlasERP.Models
{
    public partial class ObtenerBodegasResult
    {
        public int? cantidadItems { get; set; }
        public int id { get; set; }
        public string nombrebodega { get; set; }
        public string descripcion { get; set; }
        public DateTime? fecrea { get; set; }
        public string codusercrea { get; set; }
        public string ccia { get; set; }
        public string nombre { get; set; }
        public string ruc { get; set; }
        public string codcliente { get; set; }
    }
}
