// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace AtlasERP.Models
{
    public partial class obtenerGruposMarcasMaqResult
    {
        public string nombretipo { get; set; }
        public string codigotipomaq { get; set; }
        public string codmarca { get; set; }
        public string nombremarca { get; set; }
    }
}
