// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace AtlasERP.Models
{
    public partial class obtenerAgenciasCardinalResult
    {
        public string nombreCliente { get; set; }
        public DateTime? fechaCreacion { get; set; }
        public string nombreProvincia { get; set; }
        public string codProv { get; set; }
        public string nombre { get; set; }
        public string codAgencia { get; set; }
    }
}
