// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace AtlasERP.Models
{
    public partial class ObtenerAsignacionTecnicoReuqerimientoResult
    {
        public int idAsignacionTecnico { get; set; }
        public string imagen { get; set; }
        public int? idRequerimiento { get; set; }
        public string resTecnico { get; set; }
        public int? reasignacion { get; set; }
        public string nombreTecnico { get; set; }
        public string cedula { get; set; }
        public DateTime? feciniciomante { get; set; }
        public DateTime? fecfinmant { get; set; }
        public TimeOnly? horainit { get; set; }
        public TimeOnly? horafin { get; set; }
    }
}
