// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace AtlasERP.Models
{
    public partial class ObtenerDetallesVentaAperturaInterfazResult
    {
        public int idAperturaVenta { get; set; }
        public int? cantidadFacturada { get; set; }
        public int? cantidadItems { get; set; }
        [Column("sumSubtotalVenta", TypeName = "decimal(38,2)")]
        public decimal? sumSubtotalVenta { get; set; }
        [Column("totalIva", TypeName = "decimal(38,2)")]
        public decimal? totalIva { get; set; }
        [Column("sumtotalVenta", TypeName = "decimal(38,2)")]
        public decimal? sumtotalVenta { get; set; }
        [Column("cambioRecibido", TypeName = "decimal(18,2)")]
        public decimal? cambioRecibido { get; set; }
    }
}
