// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace AtlasERP.Models
{
    public partial class ObtenerTicketsRequerimientosResult
    {
        public int idTicket { get; set; }
        public string usercrea { get; set; }
        public string idAgencia { get; set; }
        public string url { get; set; }
        public string estado { get; set; }
        public string codprov { get; set; }
        public string ciudad { get; set; }
        public DateTime? fecrea { get; set; }
        public DateTime? fechainiPlanif { get; set; }
        public DateTime? fechafinPlanif { get; set; }
        public string codModelo { get; set; }
        public string area { get; set; }
        public string motivoTrabajo { get; set; }
        public string espacioSirve { get; set; }
        public string descripcionProblema { get; set; }
        public string nserieEquipo { get; set; }
        public string beneficiario { get; set; }
        public string telefono { get; set; }
        public string email { get; set; }
        public DateTime? fecreaRealIni { get; set; }
        public DateTime? fecreaRealFin { get; set; }
        public string codTipoEquipo { get; set; }
        public string codMarca { get; set; }
        public string tipoRequerimiento { get; set; }
        public TimeOnly? horaInicialReal { get; set; }
        public TimeOnly? horaFinalReal { get; set; }
        public TimeOnly? horaInicialPlanificada { get; set; }
        public TimeOnly? horaFinalPlanificada { get; set; }
        public string nombreAgencia { get; set; }
        public string codcliente { get; set; }
        public string codfrecuencia { get; set; }
        public string nombreCliente { get; set; }
        public string nombreProvincia { get; set; }
        public string nombreCanton { get; set; }
        public string nombreTipoRequerimiento { get; set; }
        public DateTime fechaActual { get; set; }
        public int? horasRestantes { get; set; }
        [Column("valor", TypeName = "decimal(10,2)")]
        public decimal? valor { get; set; }
        public string observacion { get; set; }
    }
}
