// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace AtlasERP.Models
{
    public partial class ObtenerMensajesTIcketResult
    {
        public string Usuario { get; set; }
        public string nombres { get; set; }
        public string Correo { get; set; }
        public int? idRequerimiento { get; set; }
        public DateTime? fechaemit { get; set; }
        public string mensaje { get; set; }
        public string coduser { get; set; }
        public int idmensaje { get; set; }
        public string active { get; set; }
    }
}
