// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace AtlasERP.Models
{
    public partial class ObtenerTecniCronoResult
    {
        public string provasign { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public DateTime? fecingreso { get; set; }
        public DateTime? fecsalida { get; set; }
        public string imagenPerfil { get; set; }
        public string coduser { get; set; }
        public string cedula { get; set; }
        public string cargo { get; set; }
        public string nombreEstado { get; set; }
        public int? edad { get; set; }
        public string tipo { get; set; }
        public string movilidad { get; set; }
        public string nombreMovilidad { get; set; }
        public string codcaracteristicas { get; set; }
        public string nombreCapacidad { get; set; }
        public int? valoracion { get; set; }
        public string codProvincia { get; set; }
        public string nombreProvincia { get; set; }
        public string codCanton { get; set; }
        public string nombreCanton { get; set; }
        public string codSexo { get; set; }
        public string nombreSexo { get; set; }
        public string codEstadoCivil { get; set; }
        public string nombreEstadoCivil { get; set; }
        public string codDepartamento { get; set; }
        public string nombreDepartamento { get; set; }
        public string codLicencia { get; set; }
        public string nombreLicencia { get; set; }
        public string telf { get; set; }
        public string direccion { get; set; }
    }
}
