// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace AtlasERP.Models
{
    public partial class ObtenerMedicamentosResult
    {
        public int idMedicamento { get; set; }
        public string nombre { get; set; }
        public string principioActivo { get; set; }
        public string concentracion { get; set; }
        public string formaFarmaceutica { get; set; }
        public string presentacion { get; set; }
        public string laboratorioFabricante { get; set; }
        public string paisOrigen { get; set; }
        public string registroSanitario { get; set; }
        public string lote { get; set; }
        public DateTime fechaFabricacion { get; set; }
        public DateTime fechaCaducidad { get; set; }
        public string cod_tipo_medicamento { get; set; }
        public string tipoMedicamento { get; set; }
        public string cod_via_administracion { get; set; }
        public string viaAdministracion { get; set; }
        public string indicaciones { get; set; }
        public string contraindicaciones { get; set; }
        public string efectosSecundarios { get; set; }
        public int? cantidadStock { get; set; }
        public string codUbicacionAlmacen { get; set; }
        public string ubicacionAlmacen { get; set; }
        public string temperaturaAlmacenamiento { get; set; }
        public int? minimoStock { get; set; }
        public decimal? precioUnitario { get; set; }
        public bool? requiereReceta { get; set; }
        public string receta_res { get; set; }
        public string codigoBarras { get; set; }
        public string imagenProducto { get; set; }
        public int? idPuntoVenta { get; set; }
        public string nombre_punto_venta { get; set; }
        public string instrucciones_uso { get; set; }
        public decimal? valorBlister { get; set; }
        public decimal? valorCaja { get; set; }
        public string observacion { get; set; }
        public decimal? precioCompra { get; set; }
        public decimal? descuento { get; set; }
        public decimal? oImp { get; set; }
        public decimal? contNeto { get; set; }
        public DateTime fecRegistroSistema { get; set; }
        public string userRegister { get; set; }
        public string usuarioRegistro { get; set; }
        public string codUnidadMedida { get; set; }
        public string unidadMedida { get; set; }
        public string categoria { get; set; }
        public string codcia { get; set; }
        public string mensajeCaducidad { get; set; }
        public string fgCaducidad { get; set; }
        public string bgCaducidad { get; set; }
        public int prodActivado { get; set; }
    }
}
