// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace AtlasERP.Models
{
    public partial class ObtenerCotizacionResult
    {
        public int id { get; set; }
        public string codrep { get; set; }
        public int? idRequer { get; set; }
        public int? estado { get; set; }
        public int? cantidad { get; set; }
        public decimal? valorFinal { get; set; }
        public string nombreEmpresa { get; set; }
        public string telf1 { get; set; }
        public string telf2 { get; set; }
        public string email { get; set; }
        public decimal? iva { get; set; }
        public string descripcionEmpresa { get; set; }
        public string direccion { get; set; }
        public string cargo { get; set; }
        public string nombrePersCargo { get; set; }
        public string logotipoUrl { get; set; }
        public string textoCotizacion { get; set; }
        public string firmaRepLegal { get; set; }
        public string nombreAgencia { get; set; }
        public string replegal { get; set; }
        public string nombreCliente { get; set; }
        public string nombreMarcaEquipo { get; set; }
        public string nombreModeloEquipo { get; set; }
        public string nombreTipoDeEquipo { get; set; }
        public string nombreRep { get; set; }
        public string nserie { get; set; }
        public int? contadorinicial { get; set; }
        public int? contadorfinal { get; set; }
        public string descripcionRepuesto { get; set; }
        public string ninventario { get; set; }
        public string codigobp { get; set; }
    }
}
