// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace AtlasERP.Models
{
    public partial class ObtenerDatosGeneralesPuntoVentaResult
    {
        public int id { get; set; }
        public string nombre_punto_venta { get; set; }
        public string cod_prov { get; set; }
        public string cod_canton { get; set; }
        public string direccion { get; set; }
        public string telefono { get; set; }
        public string cod_cia { get; set; }
        public DateTime fecrea { get; set; }
        public string usercrea { get; set; }
        public string nombreEmpresa { get; set; }
        public string rucEmpresa { get; set; }
        public string emailEmpresa { get; set; }
        public string direccionEmpresa { get; set; }
        public string telefonoEmpresa { get; set; }
    }
}
