// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace AtlasERP.Models
{
    public partial class ObtenerItemsBodegasResult
    {
        public string codmaquina { get; set; }
        public string marca { get; set; }
        public string nombremarca { get; set; }
        public DateTime? feccrea { get; set; }
        public int? contadorinicial { get; set; }
        public string codtipomaquina { get; set; }
        public int? contadorfinal { get; set; }
        public string nserie { get; set; }
        public string modelo { get; set; }
        public string nombremodelo { get; set; }
        public string nombremaquina { get; set; }
        public int codmaquinariabodega { get; set; }
        public string codmaquinaria { get; set; }
        public int? codbodega { get; set; }
        public DateTime? fecrea { get; set; }
        public string coduser { get; set; }
        public int? estado { get; set; }
        public string codcia { get; set; }
    }
}
