// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace AtlasERP.Models
{
    public partial class ObtenerRepuestosRequerimientosResult
    {
        public int id { get; set; }
        public string codrep { get; set; }
        public int? idRequer { get; set; }
        public DateTime fecrea { get; set; }
        public int? estado { get; set; }
        public string usercrea { get; set; }
        public string codcia { get; set; }
        public int? cantidad { get; set; }
        public string precioUnitario { get; set; }
        public decimal? valorFinal { get; set; }
        public string nombreUsuario { get; set; }
        public string nombreRep { get; set; }
        public int? marcaRep { get; set; }
        public string marcaRepuesto { get; set; }
        public string colorEstado { get; set; }
    }
}
