// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace AtlasERP.Models
{
    public partial class ObtenerVentasDetTranResult
    {
        public int idProdDet { get; set; }
        public int? codprod { get; set; }
        public int? estado { get; set; }
        public int? cantidad { get; set; }
        [Column("pvp", TypeName = "decimal(10,2)")]
        public decimal? pvp { get; set; }
        public int? idCab { get; set; }
        public string type { get; set; }
        public string nombre { get; set; }
    }
}
