// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace AtlasERP.Models
{
    public partial class ObtenerAgenciasLocalidadResult
    {
        public string zonificacion { get; set; }
        public string tipo { get; set; }
        public string telfpago { get; set; }
        public string telfclimanteni { get; set; }
        public string ruc { get; set; }
        public string replegal { get; set; }
        public string provinciaCoverturaLoc { get; set; }
        public string observacion { get; set; }
        public string nombrePago { get; set; }
        public string nombreMantenimiento { get; set; }
        public string nombreLocalidad { get; set; }
        public string nombreFrecuencia { get; set; }
        public string nombreAgencia { get; set; }
        public string longitud { get; set; }
        public string latitud { get; set; }
        public string inifrecuencia { get; set; }
        public string imagen { get; set; }
        public int? idCardi { get; set; }
        public string horarioatencionhm { get; set; }
        public string horarioatencionh { get; set; }
        public string horarioatenciondm { get; set; }
        public string horarioatenciond { get; set; }
        public DateTime? fecrea { get; set; }
        public DateTime? fechacontinicio { get; set; }
        public DateTime? fechacontfinal { get; set; }
        public DateTime? fecfinmant { get; set; }
        public string extension2 { get; set; }
        public string extension1 { get; set; }
        public int? estado { get; set; }
        public string descripcion { get; set; }
        public string correopago { get; set; }
        public string correomantenimiento { get; set; }
        public string colorfrecuencia { get; set; }
        public string coduser { get; set; }
        public string codprovincia { get; set; }
        public string codProv { get; set; }
        public string codfrecuencia { get; set; }
        public string codcliente { get; set; }
        public string codcia { get; set; }
        public string codCanton { get; set; }
        public string codagencia { get; set; }
        public int? centrocostos { get; set; }
        public string campoB { get; set; }
        public int? campoA { get; set; }
        public string agtipo { get; set; }
        public string agenciaObservacion { get; set; }
        public string agenciaDescripcion { get; set; }
        public int? cantidadMaqIngre { get; set; }
    }
}
