// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace AtlasERP.Models
{
    public partial class ObtebnerVentasCabTranResult
    {
        public int id { get; set; }
        public DateTime feccrea { get; set; }
        public string usercrea { get; set; }
        public string ccia { get; set; }
        public int? idPuntoVenta { get; set; }
        public int? estado { get; set; }
        public string observacion { get; set; }
        [Column("subtotal", TypeName = "decimal(10,2)")]
        public decimal? subtotal { get; set; }
        [Column("totalIva", TypeName = "decimal(10,2)")]
        public decimal? totalIva { get; set; }
        public string codMetodoPago { get; set; }
        public string codcli { get; set; }
        public int? idProcesoApertura { get; set; }
        public int? estadoPrint { get; set; }
        public string nombre { get; set; }
        public string direccion { get; set; }
        public string email { get; set; }
        public string ruc { get; set; }
        public string telf { get; set; }
        public string nombreCajero { get; set; }
        public string metodoPago { get; set; }
        public string nombre_punto_venta { get; set; }
    }
}
