// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace AtlasERP.Models
{
    public partial class ObtenerModulosEstantesResult
    {
        public int id { get; set; }
        public string row { get; set; }
        public string col { get; set; }
        public string description { get; set; }
        public int? estado { get; set; }
        public int? idEstante { get; set; }
        public string tokenId { get; set; }
        public string codigoPrefijo { get; set; }
        public string tagDescription { get; set; }
        public int? cajonesEstante { get; set; }
    }
}
