// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace AtlasERP.Models
{
    public partial class ObtenerConsumoAppResult
    {
        public string nombre { get; set; }
        public DateOnly? fechaconsumo { get; set; }
        public string api { get; set; }
        public string method { get; set; }
        [Column("MBconsumidos", TypeName = "decimal(38,10)")]
        public decimal? MBconsumidos { get; set; }
        [Column("segundos", TypeName = "decimal(23,8)")]
        public decimal? segundos { get; set; }
    }
}
