// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace AtlasERP.Models
{
    public partial class ObtenerMaquinariaResult
    {
        public int? numeroContrato { get; set; }
        public DateTime? fecInicialContrato { get; set; }
        public DateTime? fecfinalContrato { get; set; }
        public string descripcion { get; set; }
        public string nombreCliente { get; set; }
        public string observacion { get; set; }
        public string codmaquina { get; set; }
        public string codtipomaquina { get; set; }
        public string nombretipomaquina { get; set; }
        public string codigobp { get; set; }
        public string nserie { get; set; }
        public string codmarca { get; set; }
        public string marca { get; set; }
        public string ninventario { get; set; }
        public string codcia { get; set; }
        public int? contadorinicial { get; set; }
        public int? contadorfinal { get; set; }
        public DateTime? feccrea { get; set; }
        public string codmodelo { get; set; }
        public string modelo { get; set; }
        public int? estado { get; set; }
    }
}
