// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace AtlasERP.Models
{
    public partial class obtenerVentasPosResult
    {
        public int id { get; set; }
        public DateTime feccrea { get; set; }
        public string usercrea { get; set; }
        public string ccia { get; set; }
        public int? idPuntoVenta { get; set; }
        public int? estado { get; set; }
        public string observacion { get; set; }
        public decimal? subtotal { get; set; }
        public decimal? totalIva { get; set; }
        public string codMetodoPago { get; set; }
        public string nombreMetodoPago { get; set; }
        public string nombrePuntoVenta { get; set; }
        public decimal? totalTran { get; set; }
        public string personalVenta { get; set; }
    }
}
