// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace AtlasERP.Models
{
    public partial class ObtenerCronoResult
    {
        public int? maquinasMantenimiento { get; set; }
        public int? maquinasAsignadas { get; set; }
        public int? maquinasmanuales { get; set; }
        public string nombreTecnico { get; set; }
        public string codfrecuencia { get; set; }
        public string frecuencia { get; set; }
        public string nombreCliente { get; set; }
        public string nombreAgencia { get; set; }
        public string codcliente { get; set; }
        public string codcrono { get; set; }
        public string codusertecnic { get; set; }
        public string codagencia { get; set; }
        public string observacion { get; set; }
        public string codusercreacrono { get; set; }
        public int? semanainicio { get; set; }
        public int? mes { get; set; }
        public int? dia { get; set; }
        public int? anio { get; set; }
        public DateTime? fechamantenimiento { get; set; }
        public int? mqma { get; set; }
        public string codlocalidad { get; set; }
        public int? idRequer { get; set; }
    }
}
