// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace AtlasERP.Models
{
    public partial class ObtenerEmpresaResult
    {
        public int id { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        [Column("iva", TypeName = "decimal(10,2)")]
        public decimal? iva { get; set; }
        public string logotipo { get; set; }
        public string telf { get; set; }
        public string direccion { get; set; }
        public string type { get; set; }
        public string email { get; set; }
        public string ruc { get; set; }
    }
}
