// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace AtlasERP.Models
{
    public partial class ObtenerCLientesResult
    {
        public int? idbodega { get; set; }
        public string nombrebodega { get; set; }
        public string imagen { get; set; }
        public string extension1 { get; set; }
        public string extension2 { get; set; }
        public int? numeroAgencia { get; set; }
        public int? cantidadRequerimientos { get; set; }
        public string usuarioEncargado { get; set; }
        public string tipoContribuyente { get; set; }
        public string codcliente { get; set; }
        public string ruc { get; set; }
        public string replegal { get; set; }
        public DateTime? fechacontinicio { get; set; }
        public string nombrePago { get; set; }
        public string nombreMantenimiento { get; set; }
        public DateTime? fechacontfinal { get; set; }
        public string descripcion { get; set; }
        public string observacion { get; set; }
        public string telfclimanteni { get; set; }
        public string correomantenimiento { get; set; }
        public string telfpago { get; set; }
        public string correopago { get; set; }
        public string coduser { get; set; }
        public string codcia { get; set; }
        public string nombre { get; set; }
        public string tipo { get; set; }
    }
}
