// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AtlasERP.Models;

public partial class Prodbodegasigna
{
    public int Codmaquinariabodega { get; set; }

    public string Codmaquinaria { get; set; }

    public int? Codbodega { get; set; }

    public DateTime? Fecrea { get; set; }

    public string Coduser { get; set; }

    public int? Estado { get; set; }

    public string Codcia { get; set; }
}