// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AtlasERP.Models;

public partial class ProductosMedicamento
{
    public int IdMedicamento { get; set; }

    public string Nombre { get; set; }

    public string PrincipioActivo { get; set; }

    public string Concentracion { get; set; }

    public string FormaFarmaceutica { get; set; }

    public string Presentacion { get; set; }

    public string LaboratorioFabricante { get; set; }

    public string PaisOrigen { get; set; }

    public string RegistroSanitario { get; set; }

    public string Lote { get; set; }

    public DateOnly? FechaFabricacion { get; set; }

    public DateOnly? FechaCaducidad { get; set; }

    public string TipoMedicamento { get; set; }

    public string ViaAdministracion { get; set; }

    public string Indicaciones { get; set; }

    public string Contraindicaciones { get; set; }

    public string EfectosSecundarios { get; set; }

    public int? CantidadStock { get; set; }

    public string UbicacionAlmacen { get; set; }

    public string TemperaturaAlmacenamiento { get; set; }

    public int? MinimoStock { get; set; }

    public decimal? PrecioUnitario { get; set; }

    public bool? RequiereReceta { get; set; }

    public string CodigoBarras { get; set; }

    public string ImagenProducto { get; set; }

    public int? IdPuntoVenta { get; set; }

    public string InstruccionesUso { get; set; }

    public decimal? ValorBlister { get; set; }

    public decimal? ValorCaja { get; set; }

    public string Observacion { get; set; }

    public decimal? PrecioCompra { get; set; }

    public decimal? Descuento { get; set; }

    public decimal? OImp { get; set; }

    public decimal? ContNeto { get; set; }

    public DateTime FecRegistroSistema { get; set; }

    public string UserRegister { get; set; }

    public string UnidadMedida { get; set; }
}