// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AtlasERP.Models;

public partial class PuntoDeVentum
{
    public int Id { get; set; }

    public string NombrePuntoVenta { get; set; }

    public string CodProv { get; set; }

    public string CodCanton { get; set; }

    public string Direccion { get; set; }

    public string Telefono { get; set; }

    public string CodCia { get; set; }

    public DateTime Fecrea { get; set; }

    public string Usercrea { get; set; }

    public int? Estado { get; set; }
}