// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AtlasERP.Models;

public partial class PuntoDeVentum
{
    public int IdPuntoVenta { get; set; }

    public string NombrePuntoVenta { get; set; }

    public string CodProv { get; set; }

    public string CodCanton { get; set; }

    public string Direccion { get; set; }

    public string Telefono { get; set; }

    public string NumeroEstante { get; set; }

    public string Piso { get; set; }

    public string Cajon { get; set; }

    public string Pasillo { get; set; }

    public string CodigoUbicacion { get; set; }

    public string CodUserCargo { get; set; }

    public string TelefUserCargo { get; set; }

    public string EmailUserCargo { get; set; }

    public string CodCia { get; set; }
}