// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AtlasERP.Models;

public partial class PuntoDeVentaEstante
{
    public int Id { get; set; }

    public DateTime Fecrea { get; set; }

    public string Usercrea { get; set; }

    public int? PisosEstantes { get; set; }

    public int? CajonesEstante { get; set; }

    public string TagDescription { get; set; }

    public int? NumeroEstantesPiso { get; set; }

    public int? IdPuntoVenta { get; set; }

    public string CodigoPrefijo { get; set; }

    public int? ColumnasEstantes { get; set; }
}