// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace AtlasERP.Models
{
    public partial class ReporteMantenimientoResult
    {
        public string nombreCliente { get; set; }
        public int? Enero { get; set; }
        public int? Febrero { get; set; }
        public int? Marzo { get; set; }
        public int? Abril { get; set; }
        public int? Mayo { get; set; }
        public int? Junio { get; set; }
        public int? Julio { get; set; }
        public int? Agosto { get; set; }
        public int? Septiembre { get; set; }
        public int? Octubre { get; set; }
        public int? Noviembre { get; set; }
        public int? Diciembre { get; set; }
    }
}
