// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AtlasERP.Models;

public partial class Repuesto
{
    public string Codrep { get; set; }

    public string NombreRep { get; set; }

    public string Codigo { get; set; }

    public string UrlimagenA { get; set; }

    public DateTime Fecrea { get; set; }

    public string Usercrea { get; set; }

    public string Descripcion { get; set; }

    public string Marca { get; set; }

    public string Modelo { get; set; }

    public bool? Activo { get; set; }

    public int? MarcaRep { get; set; }

    public int? Estado { get; set; }

    public string CodTipoMaquina { get; set; }

    public string Codcia { get; set; }

    public int? CantRep { get; set; }

    public decimal? ValorCompra { get; set; }

    public decimal? PorcentajeVenta { get; set; }

    public decimal? DesccuentoAplicable { get; set; }

    public decimal? Vidautil { get; set; }
}