// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AtlasERP.Models;

public partial class TicketRequerimiento
{
    public int IdTicket { get; set; }

    public string IdAgencia { get; set; }

    public string Url { get; set; }

    public int? Estado { get; set; }

    public string Codprov { get; set; }

    public string Ciudad { get; set; }

    public DateTime? Fecrea { get; set; }

    public DateTime? FechainiPlanif { get; set; }

    public DateTime? FechafinPlanif { get; set; }

    public string Area { get; set; }

    public string MotivoTrabajo { get; set; }

    public string EspacioSirve { get; set; }

    public string DescripcionProblema { get; set; }

    public string NserieEquipo { get; set; }

    public string Beneficiario { get; set; }

    public string Telefono { get; set; }

    public string Email { get; set; }

    public DateTime? FecreaRealIni { get; set; }

    public DateTime? FecreaRealFin { get; set; }

    public string CodTipoEquipo { get; set; }

    public string CodMarca { get; set; }

    public string CodModelo { get; set; }

    public string Tipo { get; set; }

    public TimeOnly? HoraInicialReal { get; set; }

    public TimeOnly? HoraFinalReal { get; set; }

    public TimeOnly? HoraInicialPlanificada { get; set; }

    public TimeOnly? HoraFinalPlanificada { get; set; }

    public string Usercrea { get; set; }

    public decimal? Valor { get; set; }

    public string Observacion { get; set; }

    public string Ccia { get; set; }
}