// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AtlasERP.Models;

public partial class VentasposDet
{
    public int Id { get; set; }

    public int? Codprod { get; set; }

    public int? Estado { get; set; }

    public int? Cantidad { get; set; }

    public decimal? Pvp { get; set; }

    public int? IdCab { get; set; }
}