// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AtlasERP.Models;

public partial class Ventaspo
{
    public int Id { get; set; }

    public int? Idprod { get; set; }

    public DateTime Feccrea { get; set; }

    public string Usercrea { get; set; }

    public string Ccia { get; set; }

    public int? IdPuntoVenta { get; set; }

    public int? Estado { get; set; }

    public string Observacion { get; set; }

    public decimal? Subtotal { get; set; }

    public decimal? TotalIva { get; set; }

    public string CodMetodoPago { get; set; }
}