// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AtlasERP.Models;

public partial class Versionamiento
{
    public string Version { get; set; }

    public string Nombre { get; set; }

    public string Descripcion { get; set; }

    public int Id { get; set; }

    public DateTime? Fechamodular { get; set; }

    public DateTime? Fechafinal { get; set; }
}