// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AtlasERP.Models;

public partial class VersionCm
{
    public string Version { get; set; }

    public DateTime? Fechainicial { get; set; }

    public DateTime? Fechafinal { get; set; }

    public string Observacion { get; set; }
}